### ISSUE TITLE
TikZ externalize

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#12]
When using `\tikzexternalize` it might be nice to have recognizable filenames for the included artist images. Perhaps we can get the filename when someone calls `.save()` and add it to the .tex:
`\tikzsetnextfilename{ {{ filename }} }` (before the `\begin{tikzpicture}`).

Is there any downside to doing this? Maybe someone might use two images with the same name (but in different subdirectories) in one document which might cause a conflict..

**Comment by 153957** [comment]
@davidfokkema :+1: or :-1:  ?

**Comment by davidfokkema** [comment]
I'd like a recognizable prefix. Otherwise, 👍

**Comment by 153957** [comment]
Do you mean a default prefix for all artist generated images?
For instance: `\tikzsetnextfilename{ artist-{{ filename }} }`

**Comment by davidfokkema** [comment]
No, for all externalized ones. They will clutter your build directory and I like them to be recognizable.

**Comment by 153957** [comment]
Is that not what I said? Make it so the name for the externalized file will have the prefix `artist-`.
The rest of the filename will be determined by the name the user gives when saving the tex.

**Comment by davidfokkema** [comment]
I was thinking something like 'externalized'

**Comment by davidfokkema** [comment]
Oh, well. Your proposal is easy enough to spot. 👍
