### ISSUE TITLE
More colormaps?

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#22]
Commit 94b55467ef9d0cffa6c897a96fe3a2fa5c333947 adds support for a colored color map for histogram2d. Should we add more color maps or at least let the user bring his/her own?
The colormap feature is fairly simple, simply a 768 valued list of values 'grouped' by RGB (e.g. `[r0, g0, b0, r0, g0, b0, .. , r255, g255, b255]`). The grayscale values (`[0-255]`) are then mapped to those RGB values.

![multi_histogram2d](https://cloud.githubusercontent.com/assets/1433682/7336110/06de79c4-ebec-11e4-9868-af3fc4676369.png)

**Comment by davidfokkema** [comment]
That would be a nice addition.

**Comment by 153957** [comment]
Done in 089973352.

**Comment by davidfokkema** [comment]
Nice!
