### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#24]
A website with online docs/demo's would be nice..
I find Im often looking through the source code to check the docstrings.

**Comment by davidfokkema** [comment]
Me too, :-/

**Comment by 153957** [comment]
Decided on a domain yet? :) or should we just use GitHub Pages for now, it can always be linked to a domain later as we did for docs.hisparc.nl.

**Comment by davidfokkema** [comment]
Haha, no, I didn't get a domain, ;-). We'll use GitHub Pages for now, I guess.

**Comment by 153957** [comment]
Ok, for now Ill add the Makefile like we have it for `SAPPHiRE`.
But will extend it later to also generate the demo and copy the pdf result to the gh-pages.

**Comment by 153957** [comment]
http://davidfokkema.github.io/artist/

**Comment by 153957** [comment]
Fixed for now, perhaps later worry about a nice url.
