### ISSUE TITLE
Wrong pin position in loglog stopping power demo

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#26]
![screen shot 2015-04-28 at 22 46 50](https://cloud.githubusercontent.com/assets/1433682/7379904/7be9ad52-edf8-11e4-984c-872d41ed04ec.png)

**Comment by 153957** [comment]
Similar issues with cosmic-ray spectrum plot.

**Comment by davidfokkema** [comment]
Ah, great, I was just firing up an editor, ;-)

**Comment by 153957** [comment]
Haha, luckily that takes a while with Atom :D

**Comment by davidfokkema** [comment]
No longer!
