### ISSUE TITLE
Y-label in Polar plots is all over the place

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#31]
The positioning of the ylabel is not consistent for different versions of TeXLive.
In TeXLive 2015 the ylabel style needs to be `xshift=.5*\defaultwidth, yshift=-.88*\defaultheight` to be in the right place.

**Comment by 153957** [comment]
TeXLive 2013+2014 place the x and y labels in a different place than 2015.

Perhaps we can find a way to fix it for all versions.
Or usr different shifts/rotations depending on PGFPlots version (see http://tex.stackexchange.com/a/13309/41702 )

**Comment by 153957** [comment]
Not artist, but using default PGFPlots locations:

2015:
![polar_bug_texlive2015](https://cloud.githubusercontent.com/assets/1433682/8928861/7fcf5820-3521-11e5-8a4e-2e901d8bce27.png)

2013/2014:
![polar_bug_texlive2014](https://cloud.githubusercontent.com/assets/1433682/8928870/94395766-3521-11e5-9417-6216e298a956.png)

**Comment by 153957** [comment]
http://tex.stackexchange.com/questions/257437/

**Comment by 153957** [comment]
Will be fixed in pgfplots 1.13.
http://tex.stackexchange.com/a/257650/41702

The answer there also provides a nicer workaround for older versions, i.e. using absolute coordinates (well relative to the plot center).

**Comment by davidfokkema** [comment]
Glad that it will be fixed! Will using absolute coordinates work in all versions, including the new one?

**Comment by 153957** [comment]
In TeXLive it now looks fine:
![screen shot 2015-08-05 at 15 42 58](https://cloud.githubusercontent.com/assets/1433682/9087060/aa053156-3b88-11e5-9034-b55acf3f63bf.png)

Label positions in TeXLive 2014 are also fine, except that the Y label is rotated by 90°.
It no longer compiles on TeXLive 2013: `! Package PGF Math Error: Could not parse input '1.6728616e0*1.3' as a floating`..

**Comment by davidfokkema** [comment]
Then, in TL 2014 it is basically *not* fine? Or did I misunderstand? I'm OK with dropping support for TL 2013.

**Comment by 153957** [comment]
TeXLive 2014 is not fine, at least the labels are in the correct general area in both 2014/2015. But the ylabel is rotated in 2014 (like in the TL 2013/2014 plot in the comment above; https://github.com/davidfokkema/artist/issues/31#issuecomment-125539223)
Adding 'rotate=0' did not help, I could not find a way to set an absolute rotation..

**Comment by davidfokkema** [comment]
And ``rotate=-90`` or something like that did nothing? I believe it was used in the SO answer above, does that example code not work in TL 2014?

**Comment by 153957** [comment]
Yes, the label can rotated, no problem, but then it also rotates in the 2015 version, which shouldn't happen.

**Comment by davidfokkema** [comment]
Sigh.

**Comment by 153957** [comment]
We can just keep this issue open for another year, then it will be fixed automatically... :stuck_out_tongue_winking_eye:

Perhaps we need to go back to the 'hack': just place a text node for the ylabel instead of using the actual y label..

**Comment by davidfokkema** [comment]
Yes, that sounds fine. Then it'll work consistently for TL 2013/14/15, right?

**Comment by 153957** [comment]
I hope so.

**Comment by 153957** [comment]
Fixed in 0d8090465e4962f43a6240b18441dd9f2f0839f0
Might not work in the new PGFPlots 1.13 because the xlabel has a different rotation by default..
Which is the problem we have with the ylabel, there is not absolute rotation (as far as I know)
