### ISSUE TITLE
Colorbar for 2D Histograms

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#37]
It would be nice to have colorbar support for 2D histograms..
There is a colorbar support for the `scatter_table` method, but not yet for `histogram2d`.

**Comment by 153957** [comment]
See page 261 of the PGFPlots manual:

> you can also set __point meta min__ and __point meta max__ manually in order to draw a colorbar.

**Comment by davidfokkema** [comment]
Agreed, would be very nice!

**Comment by 153957** [comment]
It works, but not for multiplots, or multiple histogram2d plots in a single plot. This is because the mlimits (min/max counts in a bin) might differ between plots, this is not accounted for when making multiple plots. For each histogram2d the min/max colors are scaled between the min/max values for that plot. 

![screen shot 2016-05-04 at 16 36 13](https://cloud.githubusercontent.com/assets/1433682/15017578/6198698c-1216-11e6-934c-199ef58d286d.png)

**Comment by davidfokkema** [comment]
Great! Sometimes I think we should drop pgfplots and just use TikZ. More work, but more control.

**Comment by 153957** [comment]
The main problem with that is the 'more work' part.. (#4)

**Comment by 153957** [comment]
Mostly implemented in ea83fb9aba878bc9c9e1a424eb967cab29bf9c6d

**Comment by davidfokkema** [comment]
Nice, thanks!
