### ISSUE TITLE
Test for TeXLive 2016

### ISSUE THREAD

**Issue by 153957** [davidfokkema/artist#38]
TeXLive 2016 was released on 5 June 2016:
https://www.tug.org/texlive/

This release probably includes a newer version of PGFPlots. I am already running the latest version (latest I was able to install for TeX Live 2015) of PGFPlots as well as for some other TeX packages, newer than those that came with TeXLive 2015, and I have no issues, so it already looks promising.

**Comment by davidfokkema** [comment]
Good idea! Right now, I have issues with my thesis. I don't know if they are related to PGF/TikZ or PGFPLOTS.

**Comment by 153957** [comment]
The demo compiles successfully on TeXLive 2016.
It looks identical to the demo compiled on 2015 (using the same .tex files, since some Python scripts use random numbers).
